ALTER TABLE cards
    ADD COLUMN kind VARCHAR(16) NOT NULL DEFAULT 'text' AFTER board_id,
    ADD COLUMN image_url TEXT NULL AFTER text,
    ADD COLUMN width FLOAT NULL AFTER position_y,
    ADD COLUMN height FLOAT NULL AFTER width,
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

UPDATE cards SET kind = 'text' WHERE kind IS NULL;
